version: "2"
services:
  backend:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
       - ./backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
      - "8081:80"
    volumes:
      - ./frontend/urban-survival-guide:/frontend/urban-survival-guide

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
